# Generated by Django 4.2.2 on 2023-08-07 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_alter_ordernumberpartner_total'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deliveryMode', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='delivery.deliverymode')),
                ('orderNumber', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='order.ordernumberpartner')),
            ],
        ),
    ]
