# Generated by Django 4.2.2 on 2023-07-11 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.CharField(max_length=255)),
                ('product_price', models.IntegerField()),
                ('packaging_quantity', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_image', models.ImageField(default='media/', upload_to='product_images/')),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.productcategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveGoodsCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('receivedBY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='supplier.supplierdetailmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveGoodsCategoryModelHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivedBY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='supplier.supplierdetailmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveGoodsDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.productmodel')),
                ('receive_goods_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.receivegoodscategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveGoodsDetailHolderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.productmodel')),
                ('receive_goods_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.receivegoodscategorymodelholder')),
            ],
        ),
    ]
