# Generated by Django 4.2.2 on 2023-07-11 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('receivedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receivedcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.receivegoodscategorymodel')),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='supplier.supplierdetailmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('paidby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receivedcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.receivegoodscategorymodel')),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='supplier.supplierdetailmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='order.ordernumberpartner')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('invoice', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.orderinvoice')),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='order.ordernumberpartner')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceCaptain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.orderinvoice')),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='order.ordernumberpartner')),
            ],
        ),
        migrations.CreateModel(
            name='DebitCaptain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.orderinvoice')),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='order.ordernumberpartner')),
            ],
        ),
    ]
