# Generated by Django 4.2.2 on 2023-07-17 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierBulkDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulkamount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='supplier.supplierdetailmodel')),
            ],
        ),
        migrations.AddField(
            model_name='supplierdebit',
            name='bulkpayment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.supplierbulkdebit'),
        ),
    ]
