# Generated by Django 4.2.2 on 2023-07-17 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0002_supplierbulkdebit_supplierdebit_bulkpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierbulkdebit',
            name='paidby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
