# Generated by Django 4.2.2 on 2023-07-21 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('supplier', '0001_initial'),
        ('accounting', '0003_supplierbulkdebit_paidby'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPaymentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('bulkpayment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.supplierbulkdebit')),
                ('paidby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receivedcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.receivegoodscategorymodel')),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='supplier.supplierdetailmodel')),
            ],
        ),
    ]
