# Generated by Django 4.2.2 on 2023-08-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
        ('accounting', '0005_rename_amount_supplierpaymentbalance_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdebit',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partnerbusiness'),
        ),
    ]
