# Generated by Django 4.2.2 on 2023-07-11 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('partner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberPartnerHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=40)),
                ('orderBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='partner.partnerbusiness')),
            ],
        ),
        migrations.CreateModel(
            name='OrderNumberPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=40)),
                ('orderBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='partner.partnerbusiness')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemPartnerHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('orderNumber', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='order.ordernumberpartnerholder')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('orderNumber', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='order.ordernumberpartner')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.productmodel')),
            ],
        ),
    ]
