# Generated by Django 4.2.2 on 2023-07-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_ordernumberpartner_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernumberpartner',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
