# Generated by Django 4.2.2 on 2023-07-11 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='businessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfBusiness', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('businessLocation', models.CharField(max_length=255)),
                ('businessType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.businesstype')),
                ('registerBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('otherName', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('adminId', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partnerbusiness')),
            ],
        ),
    ]
